### ISSUE TITLE
Zend_Db_Statement_Mysqli_Exception

### ISSUE THREAD

**Issue by mbutler** [Daniel-KM/CsvImport#3]
Have tried all the various sample CSV files as well as custom CSV files with recommended settings. Running on Omeka 2.2.2

It always returns an Omeka error after Step 2: Map columns to elements, tags, or files

Zend_Db_Statement_Mysqli_Exception
Mysqli prepare error: Unknown column 'format' in 'field list'

#0 /local/vol00/srv/www/htdocs/omeka/application/libraries/Zend/Db/Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('INSERT INTO `cs...')
#1 /local/vol00/srv/www/htdocs/omeka/application/libraries/Zend/Db/Adapter/Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'INSERT INTO `cs...')
#2 /local/vol00/srv/www/htdocs/omeka/application/libraries/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('INSERT INTO `cs...')
#3 [internal function]: Zend_Db_Adapter_Abstract->query('INSERT INTO `cs...', Array)
#4 /local/vol00/srv/www/htdocs/omeka/application/libraries/Omeka/Db.php(79): call_user_func_array(Array, Array)
#5 /local/vol00/srv/www/htdocs/omeka/application/libraries/Omeka/Db.php(252): Omeka_Db->__call('query', Array)
#6 /local/vol00/srv/www/htdocs/omeka/application/libraries/Omeka/Db.php(252): Omeka_Db->query('INSERT INTO `cs...', Array)
#7 /local/vol00/srv/www/htdocs/omeka/application/libraries/Omeka/Record/AbstractRecord.php(543): Omeka_Db->insert('CsvImport_Impor...', Array)
#8 /local/vol00/srv/www/htdocs/omeka/plugins/CsvImport/models/CsvImport/Import.php(493): Omeka_Record_AbstractRecord->save()
#9 /local/vol00/srv/www/htdocs/omeka/plugins/CsvImport/controllers/IndexController.php(168): CsvImport_Import->queue()
#10 /local/vol00/srv/www/htdocs/omeka/application/libraries/Zend/Controller/Action.php(516): CsvImport_IndexController->mapColumnsAction()
#11 /local/vol00/srv/www/htdocs/omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('mapColumnsActio...')
#12 /local/vol00/srv/www/htdocs/omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#13 /local/vol00/srv/www/htdocs/omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(101): Zend_Controller_Front->dispatch()
#14 /local/vol00/srv/www/htdocs/omeka/application/libraries/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#15 /local/vol00/srv/www/htdocs/omeka/application/libraries/Omeka/Application.php(79): Zend_Application->run()
#16 /local/vol00/srv/www/htdocs/omeka/admin/index.php(28): Omeka_Application->run()
#17 {main}

**Comment by Daniel-KM** [comment]
Hi,

I do a test file each time I added a feature, that's why they are many. Each file is adapted to a specific format of import (Csv Report, Items, Files, Mixed, Update).

I use commonly CsvImport with Mixed and Update formats (without step 2, but where headers should be specified clearly in the csv file) and other formats are pretty like the official release. 

It looks like you use the official release before this fork. Have you try to fully uninstall the official release before install this one? 

Sincerely,

Daniel Berthereau
Infodoc & Knowlege management

**Comment by mbutler** [comment]
Thanks, Daniel. A full uninstall worked great.
