### ISSUE TITLE
Correct Location of config.ini for adjustments

### ISSUE THREAD

**Issue by mcarring** [Daniel-KM/CsvImport#5]
Hello, 

Hello,

Is the config.ini for omeka the one located at /omeka/application/config.ini ?

My CsvImportPlugin.php files suggests using

plugins.CsvImport.columnDelimiter = ","
plugins.CsvImport.memoryLimit = "128M"
plugins.CsvImport.requiredExtension = "txt"
plugins.CsvImport.requiredMimeType = "text/csv"
plugins.CsvImport.maxFileSize = "10M"
plugins.CsvImport.fileDestination = "/tmp"
plugins.CsvImport.batchSize = "1000"

**Comment by Daniel-KM** [comment]
Hi,

At your convenience, in the main Application/config/config.ini (recommended) or in the plugins/CsvImport/config.ini.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by mcarring** [comment]
Daniel, 

The change worked. We are now able to import up to 31 items. Do you thinks just changing the 
plugins.CsvImport.memoryLimit = "128M"

to have an increased memory of 400 MB or more will be enough to allow us to import more than 31 items? We would like to import at least 100 items at a time. 

Mary

**Comment by Daniel-KM** [comment]
Hi,

Do you use my fork or the official plugin? Memory is needed mostly for images processing and in my fork, files can be imported one by one (with manage, mixed or update modes). For my part, I use a batch size of 1 and a memory of 256 M and I can import thousands of images. 

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by mcarring** [comment]
Daniel, 

Thanks I'm using the official plug-in.

M
