### ISSUE TITLE
Automap Item Type Metadata using "Items" setting

### ISSUE THREAD

**Issue by anuragji** [Daniel-KM/CsvImport#7]
This is perhaps more of a question:

Should _Item Type_ related metadata fields get mapped automatically when using the _"Items"_ setting? 

My CSV currently includes them like  _Item Type Metadata:Owner or Custodian_, but they get ignored, while the Dublin Core formatted fields get mapped/created correctly.

**Comment by Daniel-KM** [comment]
Hi,

Here, this is simpler: the header is not good. There are typos in the header: you should use ItemType without space, RecordType without space, and Item Type Metadata:Longitude. With the sample,there is no item type, so the special columns are skipped.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by anuragji** [comment]
So the _Item Type_ metadata fields do get ignored?

**Comment by Daniel-KM** [comment]
Hi,

The Item Type column should be ItemType, the other columns are good, like "Item Type Metadata:Owner or Custodian". 

The metadata that are not in the content type are not imported by Omeka. The elements "Owner or Custodian", "Latitude", "Longitude" and "Website for Memorial" should be added to the content type "Physical object" before import.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by anuragji** [comment]
They are part of the "Physical Object" Type. And they get mapped correctly when using the _"Manage"_ option. But they get ignored using the _"Items"_ auto-mapping.

The corrected CSV used looks like:

    "RecordType","ItemType","Dublin Core:Title","Dublin Core:Creator","Dublin Core:Date","Dublin Core:Medium","Item Type Metadata:Owner or Custodian","Dublin Core:Identifier","geolocation:latitude","geolocation:longitude","geolocation:zoom_level","geolocation:map_type","geolocation:address","Item Type Metadata:Latitude","Item Type Metadata:Longitude","Item Type Metadata:Website for Memorial","File"
    "Item","Physical Object","General Pershing Statue","Haig Patagian",1922,"Bronze Scupture",,,37.771687,-122.466017,6,"Google Maps v3.x",,37.771687,-122.466017,"http://www.artandarchitecture-sf.com/?s=pershing&searchsubmit=","http://digark.us/imageserver/WWI/WEB_NW/CA_San_Francisco_Pershing_Statue.jpg"
    "Item","Physical Object","Foresters Memorial Fountain","NA",1927,"White Marble and Bronze",,,37.768328,-122.458532,6,"Google Maps v3.x",,37.768328,-122.458532,"http://www.sanfranciscodays.com/golden-gate-east/","http://digark.us/imageserver/WWI/WEB_NW/CA_Golden_Gate_Foresters.jpg"
    "Item","Physical Object","Gold Star Mothers Rock, at the center of Heroes Grove","NA",1932,"Granite Stone",,,37.771574,-122.473284,6,"Google Maps v3.x",,37.771574,-122.473284,"http://fogbay.com/2007_10_01_fog-bay_archive.html","http://digark.us/imageserver/WWI/WEB_NW/CA_GG_Park_Gold_Star_Mothers.jpg"
    "Item","Physical Object","Heroes Grove Statue","M. Earl Cummings ",1928,"Bronze",,,37.770504,-122.486121,6,"Google Maps v3.x",,37.770504,-122.486121,"http://www.artandarchitecture-sf.com/tag/heroes-redwood-grove","http://digark.us/imageserver/WWI/WEB_NW/CA_Golden_Gate_Park_Grove_of_Memory_Doughboy.jpg"

**Comment by Daniel-KM** [comment]
Hi,

You may try to update to the last release (2.1.2-full).

For my part, I use generally tabulation as delimiter and no enclosure, so I can import almost everything without issues.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by anuragji** [comment]
Thanks, I'll give that a try.

But generally speaking, it should not make a difference wether you enclose items or not, am I correct?

**Comment by Daniel-KM** [comment]
Hi,

This allows to ingest commas and double quotes, that are often present in descriptions.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management
